# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from BIS_Plot import BISPlot
from BIS_port import PortBis
from BIS_setcom import SetCOMPort
from BIS_Version import BISVersion
from BIS_offline import bis_offline
from Injection_setcom import InjectionSetCOMPort
from Injection_port import PortInjection
from BIS_Warning import BISWarning

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
###################################################################
        self.portBis = PortBis()
        self.setcomport = SetCOMPort()
        self.setingectioncomport = InjectionSetCOMPort()
        self.bisversion = BISVersion()
        self.transportdata = bis_offline()
        self.portInjection = PortInjection()
        self.biswarning = BISWarning()
###################################################################
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
##########################################################################################################
        MainWindow.setGeometry(50, 50, 1200, 700)  ###########将窗体放在桌面中心位置###########
        MainWindow.setWindowIcon(QtGui.QIcon('燕山大学.jpg'))  ##设置窗体图标
##########################################################################################################
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_11 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.datadebug_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datadebug_groupBox.sizePolicy().hasHeightForWidth())
        self.datadebug_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.datadebug_groupBox.setFont(font)
        self.datadebug_groupBox.setObjectName(_fromUtf8("datadebug_groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.datadebug_groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textBrowser_datadebug = QtGui.QTextBrowser(self.datadebug_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_datadebug.sizePolicy().hasHeightForWidth())
        self.textBrowser_datadebug.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_datadebug.setFont(font)
        self.textBrowser_datadebug.setObjectName(_fromUtf8("textBrowser_datadebug"))
        self.gridLayout_3.addWidget(self.textBrowser_datadebug, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.datadebug_groupBox)
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem)
        self.dataoperation_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataoperation_groupBox.sizePolicy().hasHeightForWidth())
        self.dataoperation_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dataoperation_groupBox.setFont(font)
        self.dataoperation_groupBox.setObjectName(_fromUtf8("dataoperation_groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dataoperation_groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.port_button = QtGui.QPushButton(self.dataoperation_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("楷体"))
        font.setBold(True)
        font.setWeight(75)
        self.port_button.setFont(font)
        self.port_button.setObjectName(_fromUtf8("port_button"))
        self.horizontalLayout_4.addWidget(self.port_button)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.clear_button = QtGui.QPushButton(self.dataoperation_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("楷体"))
        font.setBold(True)
        font.setWeight(75)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.horizontalLayout_4.addWidget(self.clear_button)
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.exit_button = QtGui.QPushButton(self.dataoperation_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("楷体"))
        font.setBold(True)
        font.setWeight(75)
        self.exit_button.setFont(font)
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.horizontalLayout_4.addWidget(self.exit_button)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.dataoperation_groupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem4)
        self.mark_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mark_groupBox.sizePolicy().hasHeightForWidth())
        self.mark_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mark_groupBox.setFont(font)
        self.mark_groupBox.setObjectName(_fromUtf8("mark_groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.mark_groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Mark11_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark11_Button.sizePolicy().hasHeightForWidth())
        self.Mark11_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark11_Button.setFont(font)
        self.Mark11_Button.setObjectName(_fromUtf8("Mark11_Button"))
        self.verticalLayout_5.addWidget(self.Mark11_Button)
        spacerItem5 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem5)
        self.Mark12_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark12_Button.sizePolicy().hasHeightForWidth())
        self.Mark12_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark12_Button.setFont(font)
        self.Mark12_Button.setObjectName(_fromUtf8("Mark12_Button"))
        self.verticalLayout_5.addWidget(self.Mark12_Button)
        self.horizontalLayout_12.addLayout(self.verticalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem7 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem7)
        self.Mark2_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark2_Button.sizePolicy().hasHeightForWidth())
        self.Mark2_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark2_Button.setFont(font)
        self.Mark2_Button.setObjectName(_fromUtf8("Mark2_Button"))
        self.verticalLayout_7.addWidget(self.Mark2_Button)
        spacerItem8 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        spacerItem9 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.Mark31_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark31_Button.sizePolicy().hasHeightForWidth())
        self.Mark31_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark31_Button.setFont(font)
        self.Mark31_Button.setObjectName(_fromUtf8("Mark31_Button"))
        self.verticalLayout_6.addWidget(self.Mark31_Button)
        spacerItem10 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem10)
        self.Mark32_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark32_Button.sizePolicy().hasHeightForWidth())
        self.Mark32_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark32_Button.setFont(font)
        self.Mark32_Button.setObjectName(_fromUtf8("Mark32_Button"))
        self.verticalLayout_6.addWidget(self.Mark32_Button)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        spacerItem11 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Mark4_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark4_Button.sizePolicy().hasHeightForWidth())
        self.Mark4_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark4_Button.setFont(font)
        self.Mark4_Button.setObjectName(_fromUtf8("Mark4_Button"))
        self.verticalLayout.addWidget(self.Mark4_Button)
        spacerItem12 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem12)
        self.Mark5_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark5_Button.sizePolicy().hasHeightForWidth())
        self.Mark5_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark5_Button.setFont(font)
        self.Mark5_Button.setObjectName(_fromUtf8("Mark5_Button"))
        self.verticalLayout.addWidget(self.Mark5_Button)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        spacerItem13 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.Mark8_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark8_Button.sizePolicy().hasHeightForWidth())
        self.Mark8_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark8_Button.setFont(font)
        self.Mark8_Button.setObjectName(_fromUtf8("Mark8_Button"))
        self.horizontalLayout_11.addWidget(self.Mark8_Button)
        spacerItem14 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.Mark6_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark6_Button.sizePolicy().hasHeightForWidth())
        self.Mark6_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark6_Button.setFont(font)
        self.Mark6_Button.setObjectName(_fromUtf8("Mark6_Button"))
        self.horizontalLayout_11.addWidget(self.Mark6_Button)
        spacerItem15 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.Mark7_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark7_Button.sizePolicy().hasHeightForWidth())
        self.Mark7_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark7_Button.setFont(font)
        self.Mark7_Button.setObjectName(_fromUtf8("Mark7_Button"))
        self.horizontalLayout_11.addWidget(self.Mark7_Button)
        spacerItem16 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.Mark9_Button = QtGui.QPushButton(self.mark_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mark9_Button.sizePolicy().hasHeightForWidth())
        self.Mark9_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mark9_Button.setFont(font)
        self.Mark9_Button.setObjectName(_fromUtf8("Mark9_Button"))
        self.horizontalLayout_11.addWidget(self.Mark9_Button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.mark_groupBox)
        self.horizontalLayout_26.addLayout(self.verticalLayout_10)
        spacerItem17 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem17)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_26.addWidget(self.line_4)
        spacerItem18 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem18)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.plot_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_groupBox.sizePolicy().hasHeightForWidth())
        self.plot_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.plot_groupBox.setFont(font)
        self.plot_groupBox.setObjectName(_fromUtf8("plot_groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.plot_groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
####################################################################################
        self.setplot = BISPlot(self.plot_groupBox)
        self.setplot.setObjectName(_fromUtf8("setplot"))
        self.gridLayout_5.addWidget(self.setplot, 0, 0, 1, 1)
####################################################################################
        self.verticalLayout_8.addWidget(self.plot_groupBox)
        spacerItem19 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem19)
        self.plotoperation_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotoperation_groupBox.sizePolicy().hasHeightForWidth())
        self.plotoperation_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plotoperation_groupBox.setFont(font)
        self.plotoperation_groupBox.setObjectName(_fromUtf8("plotoperation_groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.plotoperation_groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnStart = QtGui.QPushButton(self.plotoperation_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.horizontalLayout.addWidget(self.btnStart)
        spacerItem20 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        self.btnPause = QtGui.QPushButton(self.plotoperation_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPause.sizePolicy().hasHeightForWidth())
        self.btnPause.setSizePolicy(sizePolicy)
        self.btnPause.setObjectName(_fromUtf8("btnPause"))
        self.horizontalLayout.addWidget(self.btnPause)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem21)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.plotoperation_groupBox)
        spacerItem22 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem22)
        self.patient_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_groupBox.sizePolicy().hasHeightForWidth())
        self.patient_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.patient_groupBox.setFont(font)
        self.patient_groupBox.setObjectName(_fromUtf8("patient_groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.patient_groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.number_label = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.number_label.setFont(font)
        self.number_label.setObjectName(_fromUtf8("number_label"))
        self.horizontalLayout_8.addWidget(self.number_label)
        self.number_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_lineEdit.sizePolicy().hasHeightForWidth())
        self.number_lineEdit.setSizePolicy(sizePolicy)
        self.number_lineEdit.setObjectName(_fromUtf8("number_lineEdit"))
        self.horizontalLayout_8.addWidget(self.number_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem23 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem23)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.name_label = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.horizontalLayout_10.addWidget(self.name_label)
        self.name_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lineEdit.sizePolicy().hasHeightForWidth())
        self.name_lineEdit.setSizePolicy(sizePolicy)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.horizontalLayout_10.addWidget(self.name_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem24 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem24)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.gender_label = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gender_label.setFont(font)
        self.gender_label.setObjectName(_fromUtf8("gender_label"))
        self.horizontalLayout_9.addWidget(self.gender_label)
        self.gender_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_lineEdit.sizePolicy().hasHeightForWidth())
        self.gender_lineEdit.setSizePolicy(sizePolicy)
        self.gender_lineEdit.setObjectName(_fromUtf8("gender_lineEdit"))
        self.horizontalLayout_9.addWidget(self.gender_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_25.addLayout(self.verticalLayout_2)
        spacerItem25 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem25)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.weight_label = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.weight_label.setFont(font)
        self.weight_label.setObjectName(_fromUtf8("weight_label"))
        self.horizontalLayout_13.addWidget(self.weight_label)
        self.weight_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_lineEdit.sizePolicy().hasHeightForWidth())
        self.weight_lineEdit.setSizePolicy(sizePolicy)
        self.weight_lineEdit.setObjectName(_fromUtf8("weight_lineEdit"))
        self.horizontalLayout_13.addWidget(self.weight_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        spacerItem26 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem26)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.height_label = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.height_label.setFont(font)
        self.height_label.setObjectName(_fromUtf8("height_label"))
        self.horizontalLayout_14.addWidget(self.height_label)
        self.height_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height_lineEdit.sizePolicy().hasHeightForWidth())
        self.height_lineEdit.setSizePolicy(sizePolicy)
        self.height_lineEdit.setObjectName(_fromUtf8("height_lineEdit"))
        self.horizontalLayout_14.addWidget(self.height_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        spacerItem27 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem27)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.age_label = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.age_label.setFont(font)
        self.age_label.setObjectName(_fromUtf8("age_label"))
        self.horizontalLayout_15.addWidget(self.age_label)
        self.age_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_lineEdit.sizePolicy().hasHeightForWidth())
        self.age_lineEdit.setSizePolicy(sizePolicy)
        self.age_lineEdit.setObjectName(_fromUtf8("age_lineEdit"))
        self.horizontalLayout_15.addWidget(self.age_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_25.addLayout(self.verticalLayout_3)
        spacerItem28 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem28)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.birth_label_4 = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.birth_label_4.setFont(font)
        self.birth_label_4.setObjectName(_fromUtf8("birth_label_4"))
        self.horizontalLayout_2.addWidget(self.birth_label_4)
        self.day_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_lineEdit.sizePolicy().hasHeightForWidth())
        self.day_lineEdit.setSizePolicy(sizePolicy)
        self.day_lineEdit.setObjectName(_fromUtf8("day_lineEdit"))
        self.horizontalLayout_2.addWidget(self.day_lineEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        spacerItem29 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem29)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.birth_label_3 = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.birth_label_3.setFont(font)
        self.birth_label_3.setObjectName(_fromUtf8("birth_label_3"))
        self.horizontalLayout_6.addWidget(self.birth_label_3)
        self.month_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.month_lineEdit.sizePolicy().hasHeightForWidth())
        self.month_lineEdit.setSizePolicy(sizePolicy)
        self.month_lineEdit.setObjectName(_fromUtf8("month_lineEdit"))
        self.horizontalLayout_6.addWidget(self.month_lineEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        spacerItem30 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem30)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.birth_label_2 = QtGui.QLabel(self.patient_groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.birth_label_2.setFont(font)
        self.birth_label_2.setObjectName(_fromUtf8("birth_label_2"))
        self.horizontalLayout_7.addWidget(self.birth_label_2)
        self.year_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_lineEdit.sizePolicy().hasHeightForWidth())
        self.year_lineEdit.setSizePolicy(sizePolicy)
        self.year_lineEdit.setObjectName(_fromUtf8("year_lineEdit"))
        self.horizontalLayout_7.addWidget(self.year_lineEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_25.addLayout(self.verticalLayout_9)
        self.gridLayout_4.addLayout(self.horizontalLayout_25, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.patient_groupBox)
        self.horizontalLayout_26.addLayout(self.verticalLayout_8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_26)
        spacerItem31 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem31)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.induction_groupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.induction_groupBox.setFont(font)
        self.induction_groupBox.setObjectName(_fromUtf8("induction_groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.induction_groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.induction_Button = QtGui.QPushButton(self.induction_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.induction_Button.sizePolicy().hasHeightForWidth())
        self.induction_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.induction_Button.setFont(font)
        self.induction_Button.setObjectName(_fromUtf8("induction_Button"))
        self.gridLayout_8.addWidget(self.induction_Button, 0, 0, 1, 1)
        self.horizontalLayout_20.addWidget(self.induction_groupBox)
        spacerItem32 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem32)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_20.addWidget(self.line)
        spacerItem33 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem33)
        self.maintain_groupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.maintain_groupBox.setFont(font)
        self.maintain_groupBox.setObjectName(_fromUtf8("maintain_groupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.maintain_groupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label = QtGui.QLabel(self.maintain_groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_11.addWidget(self.label)
        spacerItem34 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem34)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.remi_lineEdit = QtGui.QLineEdit(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remi_lineEdit.sizePolicy().hasHeightForWidth())
        self.remi_lineEdit.setSizePolicy(sizePolicy)
        self.remi_lineEdit.setObjectName(_fromUtf8("remi_lineEdit"))
        self.horizontalLayout_17.addWidget(self.remi_lineEdit)
        self.label_2 = QtGui.QLabel(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_17.addWidget(self.label_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        spacerItem35 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem35)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.remistart_Button = QtGui.QPushButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.remistart_Button.setFont(font)
        self.remistart_Button.setObjectName(_fromUtf8("remistart_Button"))
        self.horizontalLayout_16.addWidget(self.remistart_Button)
        spacerItem36 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem36)
        self.remistop_Button = QtGui.QPushButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.remistop_Button.setFont(font)
        self.remistop_Button.setObjectName(_fromUtf8("remistop_Button"))
        self.horizontalLayout_16.addWidget(self.remistop_Button)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        spacerItem37 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem37)
        self.line_5 = QtGui.QFrame(self.maintain_groupBox)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_13.addWidget(self.line_5)
        spacerItem38 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem38)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_3 = QtGui.QLabel(self.maintain_groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_12.addWidget(self.label_3)
        spacerItem39 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem39)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.pro_lineEdit = QtGui.QLineEdit(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pro_lineEdit.sizePolicy().hasHeightForWidth())
        self.pro_lineEdit.setSizePolicy(sizePolicy)
        self.pro_lineEdit.setObjectName(_fromUtf8("pro_lineEdit"))
        self.horizontalLayout_18.addWidget(self.pro_lineEdit)
        self.label_4 = QtGui.QLabel(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_18.addWidget(self.label_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        spacerItem40 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem40)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.prostart_Button = QtGui.QPushButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prostart_Button.setFont(font)
        self.prostart_Button.setObjectName(_fromUtf8("prostart_Button"))
        self.horizontalLayout_19.addWidget(self.prostart_Button)
        spacerItem41 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem41)
        self.prostop_Button = QtGui.QPushButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prostop_Button.setFont(font)
        self.prostop_Button.setObjectName(_fromUtf8("prostop_Button"))
        self.horizontalLayout_19.addWidget(self.prostop_Button)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.gridLayout_7.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_20.addWidget(self.maintain_groupBox)
        spacerItem42 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem42)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_20.addWidget(self.line_2)
        spacerItem43 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem43)
        self.add_groupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_groupBox.setFont(font)
        self.add_groupBox.setObjectName(_fromUtf8("add_groupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.add_groupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.add_Button = QtGui.QPushButton(self.add_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_Button.sizePolicy().hasHeightForWidth())
        self.add_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_Button.setFont(font)
        self.add_Button.setObjectName(_fromUtf8("add_Button"))
        self.gridLayout_9.addWidget(self.add_Button, 0, 0, 1, 1)
        self.horizontalLayout_20.addWidget(self.add_groupBox)
        spacerItem44 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem44)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_20.addWidget(self.line_3)
        spacerItem45 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem45)
        self.icom_groupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.icom_groupBox.setFont(font)
        self.icom_groupBox.setObjectName(_fromUtf8("icom_groupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.icom_groupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.injection_Button = QtGui.QPushButton(self.icom_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.injection_Button.sizePolicy().hasHeightForWidth())
        self.injection_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.injection_Button.setFont(font)
        self.injection_Button.setObjectName(_fromUtf8("injection_Button"))
        self.gridLayout_10.addWidget(self.injection_Button, 0, 0, 1, 1)
        self.horizontalLayout_20.addWidget(self.icom_groupBox)
        self.verticalLayout_14.addLayout(self.horizontalLayout_20)
        self.gridLayout_11.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1362, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
###############################################
        self.statusBar()
        menubar = self.menuBar()

###############File菜单########################
        file = menubar.addMenu('&File(F)')
        self.save = QtGui.QAction('Save', self)
        file.addAction(self.save)
        self.exit = QtGui.QAction('Exit', self)
        file.addAction(self.exit)

###############Mode菜单########################
        mode = menubar.addMenu('&Mode(M)')
        self.online = QtGui.QAction('&Online', self)
        mode.addAction(self.online)
        self.offline = QtGui.QAction('Offline', self)
        mode.addAction(self.offline)

###############Option菜单########################
        option = menubar.addMenu('&Option(O)')
        self.setcom_bis = QtGui.QAction('Set BIS COM', self)
        option.addAction(self.setcom_bis)
        self.setcom_injection = QtGui.QAction('Set Injection COM', self)
        option.addAction(self.setcom_injection)

###############Version菜单########################
        version = menubar.addMenu('&Version(V)')
        self.showversion = QtGui.QAction('BIS Version', self)
        version.addAction(self.showversion)

###############Operation菜单#####################
        operation = menubar.addMenu('&Operation(O)')

        EEG = operation.addMenu('&EEG')
        self.openversion = QtGui.QAction('OpenVersion', self)
        EEG.addAction(self.openversion)
        self.sendeeg = QtGui.QAction('SendEEG', self)
        EEG.addAction(self.sendeeg)
        self.stopeeg = QtGui.QAction('StopEEG', self)
        EEG.addAction(self.stopeeg)
        self.saveeeg = QtGui.QAction('SaveEEG', self)
        EEG.addAction(self.saveeeg)
        self.sendprocessedvars = QtGui.QAction('SendVARS', self)
        EEG.addAction(self.sendprocessedvars)
        self.stopprocessedvars = QtGui.QAction('StopVARS', self)
        EEG.addAction(self.stopprocessedvars)
        self.savevars = QtGui.QAction('SaveVARS', self)
        EEG.addAction(self.savevars)

        GUI = operation.addMenu('&GUI')
        self.maingui = QtGui.QAction('MainGUI', self)
        GUI.addAction(self.maingui)
        self.minorgui = QtGui.QAction('MinorGUI', self)
        GUI.addAction(self.minorgui)

###########################################################
        self.induction_groupBox.hide()
        self.maintain_groupBox.hide()
        self.add_groupBox.hide()
        self.icom_groupBox.hide()
###########################################################
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BIS 系统", None))
        self.datadebug_groupBox.setTitle(_translate("MainWindow", "Message Record Region", None))
        self.textBrowser_datadebug.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文新魏\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'隶书\'; font-weight:400;\"><br /></p></body></html>", None))
        self.dataoperation_groupBox.setTitle(_translate("MainWindow", "Message Operation Region", None))
        self.port_button.setText(_translate("MainWindow", "Open", None))
        self.clear_button.setText(_translate("MainWindow", "Clear", None))
        self.exit_button.setText(_translate("MainWindow", "Exit", None))
        self.mark_groupBox.setTitle(_translate("MainWindow", "Mark Operation Region", None))
        self.Mark11_Button.setText(_translate("MainWindow", "诱导丙", None))
        self.Mark12_Button.setText(_translate("MainWindow", "诱导瑞", None))
        self.Mark2_Button.setText(_translate("MainWindow", "插管", None))
        self.Mark31_Button.setText(_translate("MainWindow", "维持气体", None))
        self.Mark32_Button.setText(_translate("MainWindow", "维持静脉", None))
        self.Mark4_Button.setText(_translate("MainWindow", "手术开始", None))
        self.Mark5_Button.setText(_translate("MainWindow", "手术结束", None))
        self.Mark8_Button.setText(_translate("MainWindow", "浓度改变", None))
        self.Mark6_Button.setText(_translate("MainWindow", "电刀", None))
        self.Mark7_Button.setText(_translate("MainWindow", "停药", None))
        self.Mark9_Button.setText(_translate("MainWindow", "苏醒", None))
        self.plot_groupBox.setTitle(_translate("MainWindow", "Plot Showing Region", None))
        self.plotoperation_groupBox.setTitle(_translate("MainWindow", "Plot Operation Region", None))
        self.btnStart.setText(_translate("MainWindow", "Start", None))
        self.btnPause.setText(_translate("MainWindow", "Pause", None))
        self.patient_groupBox.setTitle(_translate("MainWindow", "Patient Data Region", None))
        self.number_label.setText(_translate("MainWindow", "Ser-Num:", None))
        self.name_label.setText(_translate("MainWindow", "Name:   ", None))
        self.gender_label.setText(_translate("MainWindow", "Gender:", None))
        self.weight_label.setText(_translate("MainWindow", "Weight:", None))
        self.height_label.setText(_translate("MainWindow", "Height:", None))
        self.age_label.setText(_translate("MainWindow", "Age:", None))
        self.birth_label_4.setText(_translate("MainWindow", "Brith:Day", None))
        self.birth_label_3.setText(_translate("MainWindow", "   Month", None))
        self.birth_label_2.setText(_translate("MainWindow", "    Year", None))
        self.induction_groupBox.setTitle(_translate("MainWindow", "Induction", None))
        self.induction_Button.setText(_translate("MainWindow", "Finish", None))
        self.maintain_groupBox.setTitle(_translate("MainWindow", "Maintain", None))
        self.label.setText(_translate("MainWindow", "Remifentanil", None))
        self.label_2.setText(_translate("MainWindow", "ug/Kg/min", None))
        self.remistart_Button.setText(_translate("MainWindow", "start", None))
        self.remistop_Button.setText(_translate("MainWindow", "stop", None))
        self.label_3.setText(_translate("MainWindow", "Propofol", None))
        self.label_4.setText(_translate("MainWindow", "ug/Kg/min", None))
        self.prostart_Button.setText(_translate("MainWindow", "start", None))
        self.prostop_Button.setText(_translate("MainWindow", "stop", None))
        self.add_groupBox.setTitle(_translate("MainWindow", "Add", None))
        self.add_Button.setText(_translate("MainWindow", "Record", None))
        self.icom_groupBox.setTitle(_translate("MainWindow", "Injection", None))
        self.injection_Button.setText(_translate("MainWindow", "Start", None))

#################串口设置GUI##########################################
    def GUI_setport(self):
        self.portBis.COMport = self.setcomport.COM_comboBox.currentText()
        self.portBis.COMbaudrate = self.setcomport.baudrate_comboBox.currentText()

#################串口打开GUI##########################################
    def GUI_port_open(self):
        self.textBrowser_datadebug.append("Serial communication has been established")
        self.statusbar.showMessage("Reading serial data", 5000)
        self.port_button.setText(_translate("Form", "Close", None))

#################串口关闭GUI##########################################
    def GUI_port_close(self):
        self.textBrowser_datadebug.append("Serial communication has been closed")
        self.statusbar.showMessage("Closing serial port", 5000)
        self.port_button.setText(_translate("Form", "Open", None))

#################Injection串口设置GUI##########################################
    def GUI_setICOMport(self):
        self.portInjection.InjectionCOMport = self.setingectioncomport.COM_comboBox.currentText()
        self.portInjection.InjectionCOMbaudrate = self.setingectioncomport.baudrate_comboBox.currentText()

####################ICOM打开###########################################
    def GUI_ICOM_open(self):
        self.portInjection.flag_injectionport = True
        self.textBrowser_datadebug.append("Serial injection communication has been established")
        self.injection_Button.setText(_translate("Form", "Stop", None))

####################BISCOM###########################################
    def GUI_ICOM_close(self):
        self.portInjection.flag_injectionport = False
        self.portInjection.flag_induction = False
        self.textBrowser_datadebug.append("Serial injection communication has been closed")
        self.injection_Button.setText(_translate("Form", "Start", None))

#################清除按钮GUI##########################################
    def GUI_clear(self):
        self.textBrowser_datadebug.clear()

#################发送EEG命令GUI##########################################
    def GUI_SendEEG(self):
        self.textBrowser_datadebug.append("Send EEG Command has been sended")

#################发送Version命令GUI##########################################
    def GUI_OpenVersion(self):
        self.textBrowser_datadebug.append("Send Version Command has been sended")

#################发送EEG变量命令GUI##########################################
    def GUI_SendProcessedVARS(self):
        self.textBrowser_datadebug.append("Send Processed VARS Command has been sended")

#################停止EEG变量命令GUI##########################################
    def GUI_StopProcessedVARS(self):
        self.textBrowser_datadebug.append("Stop Processed VARS Command has been sended")

#################停止EEG命令GUI##########################################
    def GUI_StopEEG(self):
        self.textBrowser_datadebug.append("STOP EEG Command has been sended")

################保存EEG命令GUI##########################################
    def GUI_SaveEEG(self):
        self.textBrowser_datadebug.append("EEG data has been saved")

################保存BIS命令GUI##########################################
    def GUI_SaveVARS(self):
        self.textBrowser_datadebug.append("BIS data has been saved")

############病人信息#########################################
    def SavePaient(self):
        if self.portBis.flag_record:
            self.portBis.nametext = self.name_lineEdit.text()
            self.portBis.gendertext = self.gender_lineEdit.text()
            self.portBis.daytext = self.day_lineEdit.text()
            self.portBis.monthtext = self.month_lineEdit.text()
            self.portBis.yeartext = self.year_lineEdit.text()
            self.portBis.numbertext = self.number_lineEdit.text()
            self.portBis.agetext = self.age_lineEdit.text()
            self.portBis.weighttext = self.weight_lineEdit.text()
            self.portBis.heighttext = self.height_lineEdit.text()
            self.portBis.flag_record = False
        else:
            self.portBis.nametext = 'xxx'
            self.portBis.daytext = 'xx'
            self.portBis.monthtext = 'xx'
            self.portBis.yeartext = 'xxxx'
            self.portBis.numbertext = 'xxxx'


