# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main3.12.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from BIS_Plot import BISPlot
from BIS_port import PortBis
from BIS_setcom import SetCOMPort
from BIS_Version import BISVersion
from Injection_setcom import InjectionSetCOMPort
from Injection_port import PortInjection
from PID_Control import PID
from Ceff import Ceff
from Parameters import Paras

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
###################################################################
        self.portBis = PortBis()
        self.setcomport = SetCOMPort()
        self.setingectioncomport = InjectionSetCOMPort()
        self.bisversion = BISVersion()
        self.portInjection = PortInjection()
        self.pidControl = PID()
        self.ceff = Ceff()
        self.paras = Paras()
###################################################################
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
##########################################################################################################
        MainWindow.resize(1080, 900)
        # MainWindow.setGeometry(200, 100, 1350, 876)  ###########将窗体放在桌面中心位置###########
        MainWindow.setWindowIcon(QtGui.QIcon('燕山大学.jpg'))  ##设置窗体图标
##########################################################################################################
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.plot_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_groupBox.sizePolicy().hasHeightForWidth())
        self.plot_groupBox.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.plot_groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.plot_groupBox.setFont(font)
        self.plot_groupBox.setObjectName(_fromUtf8("plot_groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.plot_groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.setplot = BISPlot(self.plot_groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.setplot.setPalette(palette)
        self.setplot.setObjectName(_fromUtf8("setplot"))
        self.gridLayout_5.addWidget(self.setplot, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.plot_groupBox)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.operation_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operation_groupBox.sizePolicy().hasHeightForWidth())
        self.operation_groupBox.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.operation_groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.operation_groupBox.setFont(font)
        self.operation_groupBox.setObjectName(_fromUtf8("operation_groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.operation_groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.port_button = QtGui.QPushButton(self.operation_groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.port_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("楷体"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.port_button.setFont(font)
        self.port_button.setObjectName(_fromUtf8("port_button"))
        self.horizontalLayout.addWidget(self.port_button)
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnStart = QtGui.QPushButton(self.operation_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.horizontalLayout.addWidget(self.btnStart)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnPause = QtGui.QPushButton(self.operation_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPause.sizePolicy().hasHeightForWidth())
        self.btnPause.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPause.setFont(font)
        self.btnPause.setObjectName(_fromUtf8("btnPause"))
        self.horizontalLayout.addWidget(self.btnPause)
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.InjectionStart_Button = QtGui.QPushButton(self.operation_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InjectionStart_Button.sizePolicy().hasHeightForWidth())
        self.InjectionStart_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InjectionStart_Button.setFont(font)
        self.InjectionStart_Button.setObjectName(_fromUtf8("InjectionStart_Button"))
        self.horizontalLayout.addWidget(self.InjectionStart_Button)
        spacerItem3 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.InjectctionStop_Button = QtGui.QPushButton(self.operation_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InjectctionStop_Button.setFont(font)
        self.InjectctionStop_Button.setObjectName(_fromUtf8("InjectctionStop_Button"))
        self.horizontalLayout.addWidget(self.InjectctionStop_Button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.operation_groupBox)
        self.maintain_groupBox = QtGui.QGroupBox(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.maintain_groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.maintain_groupBox.setFont(font)
        self.maintain_groupBox.setObjectName(_fromUtf8("maintain_groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.maintain_groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.BIS40 = QtGui.QRadioButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BIS40.setFont(font)
        self.BIS40.setObjectName(_fromUtf8("BIS40"))
        self.horizontalLayout_8.addWidget(self.BIS40)
        self.BIS45 = QtGui.QRadioButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BIS45.setFont(font)
        self.BIS45.setObjectName(_fromUtf8("BIS45"))
        self.horizontalLayout_8.addWidget(self.BIS45)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.BIS60 = QtGui.QRadioButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BIS60.setFont(font)
        self.BIS60.setObjectName(_fromUtf8("BIS60"))
        self.horizontalLayout_11.addWidget(self.BIS60)
        self.BIS65 = QtGui.QRadioButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BIS65.setFont(font)
        self.BIS65.setObjectName(_fromUtf8("BIS65"))
        self.horizontalLayout_11.addWidget(self.BIS65)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.BIS50 = QtGui.QRadioButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BIS50.setFont(font)
        self.BIS50.setObjectName(_fromUtf8("BIS50"))
        self.horizontalLayout_14.addWidget(self.BIS50)
        self.BIS55 = QtGui.QRadioButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BIS55.setFont(font)
        self.BIS55.setObjectName(_fromUtf8("BIS55"))
        self.horizontalLayout_14.addWidget(self.BIS55)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.BIS70 = QtGui.QRadioButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BIS70.setFont(font)
        self.BIS70.setObjectName(_fromUtf8("BIS70"))
        self.horizontalLayout_10.addWidget(self.BIS70)
        self.BISset_Button = QtGui.QPushButton(self.maintain_groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BISset_Button.setFont(font)
        self.BISset_Button.setObjectName(_fromUtf8("BISset_Button"))
        self.horizontalLayout_10.addWidget(self.BISset_Button)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.textBrowser_Speed = QtGui.QTextBrowser(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Speed.sizePolicy().hasHeightForWidth())
        self.textBrowser_Speed.setSizePolicy(sizePolicy)
        self.textBrowser_Speed.setObjectName(_fromUtf8("textBrowser_Speed"))
        self.verticalLayout_5.addWidget(self.textBrowser_Speed)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.textBrowser_Location = QtGui.QTextBrowser(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Location.sizePolicy().hasHeightForWidth())
        self.textBrowser_Location.setSizePolicy(sizePolicy)
        self.textBrowser_Location.setObjectName(_fromUtf8("textBrowser_Location"))
        self.verticalLayout_4.addWidget(self.textBrowser_Location)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_7 = QtGui.QLabel(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_20.addWidget(self.label_7)
        self.ManControl_lineEdit = QtGui.QLineEdit(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManControl_lineEdit.sizePolicy().hasHeightForWidth())
        self.ManControl_lineEdit.setSizePolicy(sizePolicy)
        self.ManControl_lineEdit.setObjectName(_fromUtf8("ManControl_lineEdit"))
        self.horizontalLayout_20.addWidget(self.ManControl_lineEdit)
        self.label_4 = QtGui.QLabel(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_20.addWidget(self.label_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.ManStart_Button = QtGui.QPushButton(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManStart_Button.sizePolicy().hasHeightForWidth())
        self.ManStart_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ManStart_Button.setFont(font)
        self.ManStart_Button.setObjectName(_fromUtf8("ManStart_Button"))
        self.horizontalLayout_19.addWidget(self.ManStart_Button)
        self.ManStop_Button = QtGui.QPushButton(self.maintain_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManStop_Button.sizePolicy().hasHeightForWidth())
        self.ManStop_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ManStop_Button.setFont(font)
        self.ManStop_Button.setObjectName(_fromUtf8("ManStop_Button"))
        self.horizontalLayout_19.addWidget(self.ManStop_Button)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        spacerItem4 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.ICOM_button = QtGui.QPushButton(self.maintain_groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.ICOM_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("楷体"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ICOM_button.setFont(font)
        self.ICOM_button.setObjectName(_fromUtf8("ICOM_button"))
        self.horizontalLayout_6.addWidget(self.ICOM_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.ICOM_button.raise_()
        self.verticalLayout_6.addWidget(self.maintain_groupBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.patient_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_groupBox.sizePolicy().hasHeightForWidth())
        self.patient_groupBox.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.patient_groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.patient_groupBox.setFont(font)
        self.patient_groupBox.setObjectName(_fromUtf8("patient_groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.patient_groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.name_label = QtGui.QLabel(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.horizontalLayout_2.addWidget(self.name_label)
        self.name_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lineEdit.sizePolicy().hasHeightForWidth())
        self.name_lineEdit.setSizePolicy(sizePolicy)
        self.name_lineEdit.setText(_fromUtf8(""))
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.horizontalLayout_2.addWidget(self.name_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.maleButton = QtGui.QRadioButton(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maleButton.sizePolicy().hasHeightForWidth())
        self.maleButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.maleButton.setFont(font)
        self.maleButton.setObjectName(_fromUtf8("maleButton"))
        self.horizontalLayout_4.addWidget(self.maleButton)
        spacerItem5 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.femalButton = QtGui.QRadioButton(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.femalButton.sizePolicy().hasHeightForWidth())
        self.femalButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.femalButton.setFont(font)
        self.femalButton.setObjectName(_fromUtf8("femalButton"))
        self.horizontalLayout_4.addWidget(self.femalButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.date_label = QtGui.QLabel(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date_label.setFont(font)
        self.date_label.setObjectName(_fromUtf8("date_label"))
        self.horizontalLayout_7.addWidget(self.date_label)
        self.date_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_lineEdit.sizePolicy().hasHeightForWidth())
        self.date_lineEdit.setSizePolicy(sizePolicy)
        self.date_lineEdit.setObjectName(_fromUtf8("date_lineEdit"))
        self.horizontalLayout_7.addWidget(self.date_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.age_label = QtGui.QLabel(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_label.sizePolicy().hasHeightForWidth())
        self.age_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.age_label.setFont(font)
        self.age_label.setObjectName(_fromUtf8("age_label"))
        self.horizontalLayout_16.addWidget(self.age_label)
        self.age_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_lineEdit.sizePolicy().hasHeightForWidth())
        self.age_lineEdit.setSizePolicy(sizePolicy)
        self.age_lineEdit.setObjectName(_fromUtf8("age_lineEdit"))
        self.horizontalLayout_16.addWidget(self.age_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.weight_label = QtGui.QLabel(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_label.sizePolicy().hasHeightForWidth())
        self.weight_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.weight_label.setFont(font)
        self.weight_label.setObjectName(_fromUtf8("weight_label"))
        self.horizontalLayout_3.addWidget(self.weight_label)
        self.weight_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_lineEdit.sizePolicy().hasHeightForWidth())
        self.weight_lineEdit.setSizePolicy(sizePolicy)
        self.weight_lineEdit.setObjectName(_fromUtf8("weight_lineEdit"))
        self.horizontalLayout_3.addWidget(self.weight_lineEdit)
        self.weight_label_2 = QtGui.QLabel(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_label_2.sizePolicy().hasHeightForWidth())
        self.weight_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.weight_label_2.setFont(font)
        self.weight_label_2.setObjectName(_fromUtf8("weight_label_2"))
        self.horizontalLayout_3.addWidget(self.weight_label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.height_label = QtGui.QLabel(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height_label.sizePolicy().hasHeightForWidth())
        self.height_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.height_label.setFont(font)
        self.height_label.setObjectName(_fromUtf8("height_label"))
        self.horizontalLayout_15.addWidget(self.height_label)
        self.height_lineEdit = QtGui.QLineEdit(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height_lineEdit.sizePolicy().hasHeightForWidth())
        self.height_lineEdit.setSizePolicy(sizePolicy)
        self.height_lineEdit.setObjectName(_fromUtf8("height_lineEdit"))
        self.horizontalLayout_15.addWidget(self.height_lineEdit)
        self.height_label_2 = QtGui.QLabel(self.patient_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height_label_2.sizePolicy().hasHeightForWidth())
        self.height_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.height_label_2.setFont(font)
        self.height_label_2.setObjectName(_fromUtf8("height_label_2"))
        self.horizontalLayout_15.addWidget(self.height_label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.patient_groupBox)
        self.datadebug_groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datadebug_groupBox.sizePolicy().hasHeightForWidth())
        self.datadebug_groupBox.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.datadebug_groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.datadebug_groupBox.setFont(font)
        self.datadebug_groupBox.setObjectName(_fromUtf8("datadebug_groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.datadebug_groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textBrowser_datadebug = QtGui.QTextBrowser(self.datadebug_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_datadebug.sizePolicy().hasHeightForWidth())
        self.textBrowser_datadebug.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser_datadebug.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("华文新魏"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_datadebug.setFont(font)
        self.textBrowser_datadebug.setObjectName(_fromUtf8("textBrowser_datadebug"))
        self.gridLayout_3.addWidget(self.textBrowser_datadebug, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.datadebug_groupBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.gridLayout_6.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
###############################################
        self.statusBar()
        menubar = self.menuBar()

###############File菜单########################
        file = menubar.addMenu('&File(F)')
        self.clear = QtGui.QAction('Clear', self)
        file.addAction(self.clear)
        self.exit = QtGui.QAction('Exit', self)
        file.addAction(self.exit)

###############Mode菜单########################
        mark = menubar.addMenu('&Mark(M)')
        self.propofol = QtGui.QAction('Propofol', self)
        mark.addAction(self.propofol)
        self.reminfentanil = QtGui.QAction('Reminfentanil', self)
        mark.addAction(self.reminfentanil)
        self.cannula = QtGui.QAction('Cannula', self)
        mark.addAction(self.cannula)
        self.maintain_gas = QtGui.QAction('Maintain-Gas', self)
        mark.addAction(self.maintain_gas)
        self.maintain_liquid = QtGui.QAction('Maintain-Liquid', self)
        mark.addAction(self.maintain_liquid)
        self.operation_start = QtGui.QAction('Operation-Start', self)
        mark.addAction(self.operation_start)
        self.operation_end = QtGui.QAction('Operation-End', self)
        mark.addAction(self.operation_end)
        self.electrotome = QtGui.QAction('Electrotome', self)
        mark.addAction(self.electrotome)
        self.drug_stop = QtGui.QAction('Drug-Stop', self)
        mark.addAction(self.drug_stop)
        self.awake = QtGui.QAction('Awake', self)
        mark.addAction(self.awake)
        self.change = QtGui.QAction('Change', self)
        mark.addAction(self.change)

###############Option菜单########################
        option = menubar.addMenu('&Option(O)')
        self.setcom_bis = QtGui.QAction('Set BIS COM', self)
        option.addAction(self.setcom_bis)
        self.setcom_injection = QtGui.QAction('Set Injection COM', self)
        option.addAction(self.setcom_injection)

###############Version菜单########################
        version = menubar.addMenu('&Version(V)')
        self.showversion = QtGui.QAction('BIS Version', self)
        version.addAction(self.showversion)

###############Operation菜单#####################
        operation = menubar.addMenu('&Operation(O)')
        Save = operation.addMenu('&Save')
        self.Export_data = QtGui.QAction('Export-data', self)
        Save.addAction(self.Export_data)
        self.Export_finish = QtGui.QAction('Export-finish', self)
        Save.addAction(self.Export_finish)
        self.savepatient = QtGui.QAction('SavePatient', self)
        Save.addAction(self.savepatient)

###############################################
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AC-Control System", None))
        self.plot_groupBox.setTitle(_translate("MainWindow", "Plot Showing Region", None))
        self.operation_groupBox.setTitle(_translate("MainWindow", "Operation Region", None))
        self.port_button.setText(_translate("MainWindow", "Open-COM", None))
        self.btnStart.setText(_translate("MainWindow", "Begin-Plot", None))
        self.btnPause.setText(_translate("MainWindow", "Pause-Plot", None))
        self.InjectionStart_Button.setText(_translate("MainWindow", "Start-Injection", None))
        self.InjectctionStop_Button.setText(_translate("MainWindow", "Stop-Injection", None))
        self.maintain_groupBox.setTitle(_translate("MainWindow", "Injection Region", None))
        self.BIS40.setText(_translate("MainWindow", "BIS-40", None))
        self.BIS45.setText(_translate("MainWindow", "BIS-45", None))
        self.BIS60.setText(_translate("MainWindow", "BIS-60", None))
        self.BIS65.setText(_translate("MainWindow", "BIS-65", None))
        self.BIS50.setText(_translate("MainWindow", "BIS-50", None))
        self.BIS55.setText(_translate("MainWindow", "BIS-55", None))
        self.BIS70.setText(_translate("MainWindow", "BIS-70", None))
        self.BISset_Button.setText(_translate("MainWindow", "set", None))
        self.label.setText(_translate("MainWindow", "Speed", None))
        self.textBrowser_Speed.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文新魏\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt; font-weight:400;\"><br /></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "Location", None))
        self.label_7.setText(_translate("MainWindow", "Man-Control:", None))
        self.label_4.setText(_translate("MainWindow", "ml/min", None))
        self.ManStart_Button.setText(_translate("MainWindow", "ManConrol-Start", None))
        self.ManStop_Button.setText(_translate("MainWindow", "ManControl-Stop", None))
        self.ICOM_button.setText(_translate("MainWindow", "Open-InjectCOM", None))
        self.patient_groupBox.setTitle(_translate("MainWindow", "Patient Data Region", None))
        self.name_label.setText(_translate("MainWindow", "Name:", None))
        self.maleButton.setText(_translate("MainWindow", "Male", None))
        self.femalButton.setText(_translate("MainWindow", "Female", None))
        self.date_label.setText(_translate("MainWindow", "D a t e:", None))
        self.age_label.setText(_translate("MainWindow", "A g e : ", None))
        self.weight_label.setText(_translate("MainWindow", "Weight:", None))
        self.weight_label_2.setText(_translate("MainWindow", "kg", None))
        self.height_label.setText(_translate("MainWindow", "Height:", None))
        self.height_label_2.setText(_translate("MainWindow", "cm", None))
        self.datadebug_groupBox.setTitle(_translate("MainWindow", "Message Record Region", None))
        self.textBrowser_datadebug.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文新魏\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

#################参数GUI##########################################
    def GUI_Para(self):
        self.textBrowser_Speed.append(str(self.paras.localtime) + "\n" + "BIS/Ceff/Speed:" + "\n" + str(self.portBis.bisvalue) + "\t" + str(self.paras.ceffinal) + "\t" + str(self.paras.Speed) + "m/h")

#################BIS设置GUI##########################################
    def GUI_BISSET(self):
        self.textBrowser_datadebug.append("Expected BIS Value is " + str(self.portBis.bisvalue_expect))

#################开始注射GUI##########################################
    def GUI_InjectStart(self):
        self.textBrowser_datadebug.append("Started the Auto Injection")

#################停止注射GUI##########################################
    def GUI_InjectStop(self):
        self.textBrowser_datadebug.append("Stopped the Auto Injection")

#################开始Man-ControlGUI###################################
    def GUI_StartMC(self):
        self.paras.MCtext = self.ManControl_lineEdit.text()
        self.portInjection.ManSpeed = float('%.1f' % float(self.paras.MCtext))
        self.textBrowser_datadebug.append("Started Man-Control")

#################停止Man-ControlGUI##########################################
    def GUI_StopMC(self):
        self.textBrowser_datadebug.append("Stopped Man-Control")

#################串口设置GUI##########################################
    def GUI_setport(self):
        self.portBis.COMport = self.setcomport.COM_comboBox.currentText()
        self.portBis.COMbaudrate = self.setcomport.baudrate_comboBox.currentText()

#################串口打开GUI##########################################
    def GUI_port_open(self):
        self.textBrowser_datadebug.append("Serial communication has been established")
        self.statusbar.showMessage("Reading serial data", 5000)
        self.port_button.setText(_translate("Form", "Close-COM", None))

#################串口关闭GUI##########################################
    def GUI_port_close(self):
        self.textBrowser_datadebug.append("Serial communication has been closed")
        self.statusbar.showMessage("Closing serial port", 5000)
        self.port_button.setText(_translate("Form", "Open-COM", None))

#################Injection串口设置GUI##########################################
    def GUI_setICOMport(self):
        self.portInjection.InjectionCOMport = self.setingectioncomport.COM_comboBox.currentText()
        self.portInjection.InjectionCOMbaudrate = self.setingectioncomport.baudrate_comboBox.currentText()

####################ICOM打开###########################################
    def GUI_ICOM_open(self):
        self.portInjection.flag_ICOM = True
        self.textBrowser_datadebug.append("Serial injection communication has been established")
        self.ICOM_button.setText(_translate("Form", "Stop-InjectCOM", None))

####################BISCOM###########################################
    def GUI_ICOM_close(self):
        self.portInjection.flag_ICOM = False
        self.textBrowser_datadebug.append("Serial injection communication has been closed")
        self.ICOM_button.setText(_translate("Form", "Open-InjectCOM", None))

#################清除按钮GUI##########################################
    def GUI_clear(self):
        self.textBrowser_datadebug.clear()

#################发送Version命令GUI##########################################
    def GUI_OpenVersion(self):
        self.textBrowser_datadebug.append("Send Version Command has been sended")

#################发送EEG变量命令GUI##########################################
    def GUI_SendBIS(self):
        self.textBrowser_datadebug.append("Send Processed BIS Command has been sended")

#################停止EEG变量命令GUI##########################################
    def GUI_StopBIS(self):
        self.textBrowser_datadebug.append("Stop Processed BIS Command has been sended")

################保存BIS命令GUI##########################################
    def GUI_SaveBIS(self):
        self.textBrowser_datadebug.append("BIS data has been saved")

################保存病人信息命令GUI##########################################
    def GUI_SavePatient(self):
        self.textBrowser_datadebug.append("Patient data has been saved")

################病人信息##########################################
    def PatientData(self):
        self.portBis.nametext = self.name_lineEdit.text()
        self.portBis.datatext = self.date_lineEdit.text()
        self.portBis.agetext = self.age_lineEdit.text()
        self.portBis.weighttext = self.weight_lineEdit.text()
        self.portBis.heighttext = self.height_lineEdit.text()
        if self.maleButton.isChecked():
            self.portBis.gendertext = 'male'
        if self.femalButton.isChecked():
            self.portBis.gendertext = 'female'
        else:
            pass
